
name: 'Reviewdog Rubocop Action'
description: 'A GitHub Action that lints your Ruby code with Rubocop and outputs to the PR with Reviewdog!'
author: 'Andrew Mason <andrewmcodes@protonmail.com>'
env:
  REVIEWDOG_GITHUB_API_TOKEN: # ${{ secrets.GITHUB_TOKEN }}
inputs:
  bundle:
    description: "Boolean value that toggles gem installing rubocop gems or running bundle install"
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bundle }}
branding:
  icon: 'code'
  color: 'blue'
