name: Reviewdog Rubocop Action

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  rubocop:
    name: Run Reviewdog Rubocop Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: reviewdog-rubocop-action
        uses: andrewmcodes/reviewdog-rubocop-action@8d7fbc931705662fd42193eb0d276799da972d7a
        with:
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
