name: Reviewdog Rubocop Action

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  no_variables:
    name: Run Reviewdog Rubocop Action with no variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: reviewdog-rubocop-action
        uses: './'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  input_bundle:
    name: Run Reviewdog Rubocop Action with bundle input
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: reviewdog-rubocop-action
        uses: './'
        with:
          bundle: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
